FROM bellsoft/liberica-openjdk-alpine:17 as build
WORKDIR /workspace/app

COPY app/build/libs/ .
RUN mkdir -p target/extracted
RUN java -Djarmode=layertools -jar *.jar extract --destination target/extracted

FROM bellsoft/liberica-openjdk-alpine:17
VOLUME /tmp
ARG EXTRACTED=/workspace/app/target/extracted

COPY --from=build ${EXTRACTED}/dependencies/ ./
COPY --from=build ${EXTRACTED}/spring-boot-loader/ ./
COPY --from=build ${EXTRACTED}/snapshot-dependencies/ ./
COPY --from=build ${EXTRACTED}/application/ ./

ENV SPRING_PROFILES_ACTIVE=dev
ENTRYPOINT java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} org.springframework.boot.loader.launch.JarLauncher